### ISSUE TITLE
编辑用户，保存后无反应，F12查看显示toaster未定义

### ISSUE THREAD

**Issue by 39627020** [iBase4J/iBase4J#55]
登录进去后，选择编辑用户，保存后无反应，F12查看发现updateController.js里面toaster未定义，查看数据库发现数据已经更新完成，日志也正常。
![bug](https://user-images.githubusercontent.com/14237411/30908653-d8256096-a3b0-11e7-9314-ebc5b58aefe1.jpg)

**Comment by iBase4J** [comment]
应该是跳转有问题
